# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('nombre', models.CharField(max_length=70, verbose_name='Nombre y Apellido')),
                ('cedula', models.IntegerField(primary_key=True, serialize=False, verbose_name='Cedula')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('titulacion', models.CharField(max_length=70, verbose_name='Titulación o Nivel de Estudios')),
                ('tipo', models.CharField(choices=[('FJ', 'Fijo / Contratado'), ('PR', 'Provisional'), ('DE', 'Deporte'), ('SU', 'Suplente'), ('OT', 'Otro')], max_length=18, verbose_name='Tipo')),
                ('telefono1', models.CharField(blank=True, max_length=12, verbose_name='Teléfono Fijo')),
                ('telefono2', models.CharField(blank=True, max_length=12, verbose_name='Teléfono Móvil')),
                ('telefono3', models.CharField(blank=True, max_length=12, verbose_name='Otro Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('nombre', models.CharField(help_text='Nombre y Apellidos del Estudiante', max_length=70, verbose_name='Nombre y Apellido')),
                ('cedula', models.IntegerField(help_text='Cedula del Estudiante', primary_key=True, serialize=False, verbose_name='Cedula')),
                ('fechaNacimiento', models.DateField(help_text='Fecha de Nacimiento del Estudiante', verbose_name='Fecha de Nacimiento')),
                ('lugarNacimiento', models.CharField(help_text='Lugar de Nacimiento del Estudiante', max_length=70, verbose_name='Lugar de Nacimiento')),
                ('gender', models.BooleanField(help_text='Genero o Sexo del Estudiante', verbose_name='Sexo')),
                ('edad', models.IntegerField(help_text='Edad del Estudiante', verbose_name='Edad')),
                ('direccion', models.TextField(help_text='Dirección del Estudiante', verbose_name='Dirección')),
                ('ultimoGrado', models.CharField(choices=[('IN', 'Inicial'), ('N1', 'Kinder Garden Nivel 1'), ('N2', 'Kinder Garden Nivel 2'), ('N3', 'Kinder Garden Nivel 3'), ('G1', '1er Grado'), ('G2', '2do Grado'), ('G3', '3er Grado'), ('G4', '4to Grado'), ('G5', '5to Grado'), ('G6', '6to Grado')], help_text='Último Grado Cursado Aprobado', max_length=22, verbose_name='Último Grado Cursado')),
                ('lugarUltimo', models.CharField(help_text='Lugar Donde Cursó Último Grado Aprobado', max_length=70, verbose_name='Lugar de Último Grado Cursado')),
                ('a_oUltimo', models.IntegerField(help_text='Año Donde Cursó Último Grado Aprobado', verbose_name='Año Utlimo Grado Cursado')),
                ('nombrePadre', models.CharField(blank=True, max_length=70, verbose_name='Nombr y Apellido del Padre')),
                ('cedulaPadre', models.IntegerField(blank=True, verbose_name='Cedula del Padre')),
                ('tlfPadre', models.CharField(blank=True, max_length=12, verbose_name='Telefono del Padre')),
                ('nombreMadre', models.CharField(blank=True, max_length=70, verbose_name='Nombr y Apellido de la Madre')),
                ('cedulaMadre', models.IntegerField(blank=True, verbose_name='Cedula de la Madre')),
                ('tlfMadre', models.CharField(blank=True, max_length=12, verbose_name='Telefono de la Madre')),
            ],
            options={
                'ordering': ['-nombre'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_o', models.IntegerField(verbose_name='Año')),
                ('fechaInicial', models.DateField(verbose_name='Fecha Inicial')),
                ('fechaCulminacion', models.DateField(verbose_name='Fecha de Culminación')),
                ('totalEstudiantes', models.IntegerField(verbose_name='Total Estudiantes Inscritos')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('IN', 'Inicial'), ('N1', 'Kinder Garden Nivel 1'), ('N2', 'Kinder Garden Nivel 2'), ('N3', 'Kinder Garden Nivel 3'), ('G1', '1er Grado'), ('G2', '2do Grado'), ('G3', '3er Grado'), ('G4', '4to Grado'), ('G5', '5to Grado'), ('G6', '6to Grado')], max_length=22, verbose_name='Grado o Nivel')),
                ('Codigo', models.IntegerField(verbose_name='Código')),
                ('Descripcion', models.TextField(blank=True, verbose_name='Descripcion General')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion_Abierta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula', models.CharField(max_length=15, verbose_name='Aula')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolManagerSS.Docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolManagerSS.Periodo')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SchoolManagerSS.Seccion')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='Inscripcion',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inscrito', to='SchoolManagerSS.Seccion_Abierta'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='seccionesCursadas',
            field=models.ManyToManyField(blank=True, related_name='Cursadas', to='SchoolManagerSS.Seccion_Abierta'),
        ),
    ]
