# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-02 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolManagerSS', '0002_auto_20160402_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='totalEstudiantes',
            field=models.IntegerField(default=0, verbose_name='Total Estudiantes Inscritos'),
        ),
    ]
